services:
  database:
    image: postgres:15-alpine
    container_name: realestate_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: realestate-api:latest
    container_name: realestate_api_container
    ports:
      - "8080:8080"
    env_file:
      - .env
      - api/.env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}

      DB_HOST: database

      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      JWK_SET_URI: http://auth-server:9000/oauth2/jwks

    depends_on:
      database:
        condition: service_healthy
    restart: always

  auth-server:
    build:
      context: .
      dockerfile: auth-server/Dockerfile
    image: realestate-auth-server:latest
    container_name: realestate_auth_server_container
    ports:
      - "9000:9000"
    env_file:
      - .env
      - auth-server/.env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}

      DB_HOST: database

      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      database:
        condition: service_healthy

    volumes:
      - ./auth-server/secrets:/app/secrets:ro
    restart: always

volumes:
  postgres_data:
