real-estate.oauth2.postman.client-id=${POSTMAN_CLIENT_ID:postman-client}
real-estate.oauth2.postman.client-secret=${POSTMAN_CLIENT_SECRET:postman-secret}
real-estate.oauth2.postman.redirect-uri=${POSTMAN_REDIRECT_URI:https://oauth.pstmn.io/v1/browser-callback}

real-estate.oauth2.swagger.client-id=${SWAGGER_CLIENT_ID:swagger-client}
real-estate.oauth2.swagger.redirect-uri=${SWAGGER_REDIRECT_URI:http://localhost:8080/swagger-ui/oauth2-redirect.html}
real-estate.oauth2.swagger.ui-origin=${SWAGGER_UI_ORIGIN:http://localhost:8080}
