spring.application.name=auth-server
server.port=9000
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:real_estate}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

real-estate.oauth2.bff.client-id=${BFF_CLIENT_ID:real-estate-bff}
real-estate.oauth2.bff.client-secret=${BFF_CLIENT_SECRET:bff-secret}
real-estate.oauth2.bff.redirect-uri=${BFF_REDIRECT_URI:http://localhost:8080/login/oauth2/code/real-estate-bff}
real-estate.oauth2.bff.post-logout-redirect-uri=${BFF_POST_LOGOUT_REDIRECT_URI:http://localhost:3000}

security.jwt.public-key=${JWT_PUBLIC_KEY:file:./secrets/app.pub}
security.jwt.private-key=${JWT_PRIVATE_KEY:file:./secrets/app.key}

security.authorization-server.url=${AUTHORIZATION_SERVER_URL:http://localhost:9000}

security.jwt.token-duration.refresh=${JWT_REFRESH_TOKEN_DURATION:604800}
security.jwt.token-duration.access=${JWT_ACCESS_TOKEN_DURATION:8000}
