spring.application.name=bff

server.port=8081
server.servlet.session.cookie.name=BFFSESSION

spring.security.oauth2.client.registration.real-estate-bff.client-id=${BFF_CLIENT_ID:real-estate-bff}
spring.security.oauth2.client.registration.real-estate-bff.client-secret=${BFF_CLIENT_SECRET:bff-secret}
spring.security.oauth2.client.registration.real-estate-bff.redirect-uri=${BFF_REDIRECT_URI:http://localhost:8081/login/oauth2/code/real-estate-bff}
spring.security.oauth2.client.registration.real-estate-bff.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.real-estate-bff.scope[0]=openid
spring.security.oauth2.client.registration.real-estate-bff.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.real-estate-bff.provider=auth-server
spring.security.oauth2.client.provider.auth-server.authorization-uri=${AUTH_URI:http://localhost:9000/oauth2/authorize}
spring.security.oauth2.client.provider.auth-server.token-uri=${TOKEN_URI:http://localhost:9000/oauth2/token}
spring.security.oauth2.client.provider.auth-server.jwk-set-uri=${JWK_SET_URI:http://localhost:9000/oauth2/jwks}
real-estate.bff.frontend-url=${FRONTEND_URL:http://localhost:3000}
real-estate.bff.api-url=${API_URL:http://localhost:8080}
real-estate.bff.logout-uri=${LOGOUT_URI:http://localhost:9000/connect/logout}